apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httproute
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - web.atayi.net
        - atayi.net
      secretName: web-tls
  rules:
    - host: atayi.net
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: webservice
                port:
                  number: 8080

    - host: web.atayi.net
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: webservice
                port:
                  number: 8080
