apiVersion: apps/v1
kind: Deployment
metadata:
  name: spdf
spec:
  selector:
    matchLabels:
      app: spdf
  template:
    metadata:
      labels:
        app: spdf
    spec:
      containers:
        - name: spdf
          image: stirlingtools/stirling-pdf:latest
          ports:
            - name: http
              containerPort: 8080
