apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: descheduler
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Namilaus/argocd_platform.git
    targetRevision: HEAD
    path: platform/descheduler
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
