apiVersion: apps/v1
kind: Deployment
metadata:
  name: stalwart
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stalwart
  template:
    metadata:
      labels:
        app: stalwart
    spec:
      containers:
        - name: stalwart
          image: stalwartlabs/stalwart:v0.16
          args:
            - "--config"
            - "/etc/stalwart/config.json"
          ports:
            - name: smtps
              containerPort: 465
            - name: imaps
              containerPort: 993
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/stalwart/config.json
              subPath: config.json
              readOnly: true
            - name: tls
              mountPath: /etc/stalwart/tls
              readOnly: true
            - name: data
              mountPath: /var/lib/stalwart

      volumes:
        - name: config
          configMap:
            name: stalwart-config
        - name: tls
          secret:
            secretName: stalwart-tls
        - name: data
          emptyDir: {}
