apiVersion: apps/v1
kind: Deployment
metadata:
  name: stalwart
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stalwart
  template:
    metadata:
      labels:
        app: stalwart
    spec:
      containers:
        - name: stalwart
          image: stalwartlabs/stalwart:v0.16
          # envFrom:
          #   - secretRef:
          #       name: stalwart-env
          ports:
            - name: smtps
              containerPort: 465
            - name: imaps
              containerPort: 993
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/stalwart/config.json
              subPath: config.json
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: stalwart-config
