apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httproute
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    argocd.argoproj.io/sync-wave: "2"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - mail.atayi.net
      secretName: stalwart-tls
  rules:
    - host: mail.atayi.net
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: stalwart-service
                port:
                  name: http
