apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stalwart-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path # k3s default local-path provisioner
  resources:
    requests:
      storage: 10Gi
