apiVersion: v1
kind: Service
metadata:
  name: stalwart-service
spec:
  selector:
    app: stalwart
  ports:
    - port: 8080
      targetPort: http
    - port: 465
      targetPort: smtps
    - port: 993
      targetPort: imaps
