apiVersion: v1
kind: Service
metadata:
  name: netbird-server-service
spec:
  selector:
    app: netbird-server
  ports:
    - port: 3478
      targetPort: 3478
      protocol: UDP
    - port: 80
      targetPort: 80
