apiVersion: v2
name: argocd-image-updater
description: Helm chart for argocd-image-updater
type: application
version: 1.0.0

dependencies:
  - name: argocd-image-updater
    version: 1.2.4
    repository: oci://ghcr.io/argoproj/argo-helm
