apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-grcp
  labels:
    app.kubernetes.io/name: http
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    argocd.argoproj.io/sync-wave: "1"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.priority: "10"
    traefik.ingress.kubernetes.io/service.serversscheme: h2c

spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - netbird-mgmt.atayi.net
      secretName: netbird-tls
  rules:
    - host: netbird-mgmt.atayi.net
      http:
        paths:
          - pathType: Prefix
            path: "/management.ManagementService/"
            backend:
              service:
                name: netbird-server-service
                port:
                  name: http
          - pathType: Prefix
            path: "/signalexchange.SignalExchange/"
            backend:
              service:
                name: netbird-server-service
                port:
                  name: http
          - pathType: Prefix
            path: "/management.ProxyService/"
            backend:
              service:
                name: netbird-server-service
                port:
                  name: http
