apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-dashboard.yaml
  - service-dashboard.yaml
  - deployment-server.yaml
  - service-server.yaml
  - http.yaml
  - pvc.yaml
  - service-stun.yaml
  - http-grpc.yaml
  - service-server-grpc.yaml
