apiVersion: v1
kind: Service
metadata:
  name: netbird-server-grpc-service
  annotations:
    traefik.ingress.kubernetes.io/service.serversscheme: h2c
spec:
  selector:
    app: netbird-server
  ports:
    - name: grpc
      port: 80
      targetPort: http
