apiVersion: v1
kind: Service
metadata:
  name: netbird-stun
spec:
  type: LoadBalancer
  selector:
    app: netbird-server
  ports:
    - name: stun
      port: 3478
      targetPort: stun
      protocol: UDP
